// Initial mock data mirroring the reference design for Global Student Connect

export const INITIAL_STUDENT_PROFILE = {
  id: 'usr_ruthvik_01',
  name: 'Ruthvik Reddy',
  email: 'ruthvik@example.com',
  country: 'India',
  countryCode: 'IN',
  flag: '🇮🇳',
  age: 19,
  educationLevel: 'College / University',
  institution: 'Delhi Technological University',
  timezone: 'Asia/Kolkata (IST +5:30)',
  bio: 'I love technology, sports, and learning about different cultures and making friends across borders!',
  avatar: '🧑‍💻',
  completionPercentage: 80,
  isProfileComplete: true,
  interests: ['Technology', 'Science', 'Sports', 'Culture'],
  languages: ['English', 'Hindi', 'Telugu'],
  stats: {
    totalMatches: 14,
    upcomingCalls: 1,
    reflections: 6,
    countriesConnected: 8,
  },
  upcomingCall: {
    id: 'sess_01',
    partnerName: 'Yuki Sato',
    partnerCountry: 'Japan',
    partnerFlag: '🇯🇵',
    partnerAvatar: '👩‍🎨',
    date: 'Tomorrow, 4:00 PM',
    topic: 'Student Life in Tokyo vs New Delhi',
    meetingId: 'meet-yuki-ruthvik',
  }
};

export const ALL_INTERESTS_LIST = [
  { id: 'tech', name: 'Technology', icon: 'Laptop' },
  { id: 'science', name: 'Science', icon: 'FlaskConical' },
  { id: 'sports', name: 'Sports', icon: 'Trophy' },
  { id: 'art', name: 'Art', icon: 'Palette' },
  { id: 'travel', name: 'Travel', icon: 'Plane' },
  { id: 'books', name: 'Book Stories', icon: 'BookOpen' },
  { id: 'culture', name: 'Culture', icon: 'Globe' },
  { id: 'education', name: 'Education', icon: 'GraduationCap' },
  { id: 'environment', name: 'Environment', icon: 'Leaf' },
  { id: 'food', name: 'Food & Cooking', icon: 'Utensils' },
  { id: 'photography', name: 'Photography', icon: 'Camera' },
  { id: 'music', name: 'Music', icon: 'Music' },
  { id: 'gaming', name: 'Gaming', icon: 'Gamepad2' },
  { id: 'other', name: 'Other', icon: 'Sparkles' },
];

export const MOCK_MATCHES = [
  {
    id: 'match_yuki_01',
    name: 'Yuki Sato',
    age: 19,
    country: 'Japan',
    countryCode: 'JP',
    flag: '🇯🇵',
    educationLevel: 'University',
    institution: 'Waseda University, Tokyo',
    matchScore: 92,
    avatar: '👩‍🎨',
    gallery: ['🎨 Digital Art', '🍵 Tea Culture', '🤖 Robotics Club'],
    interests: ['Music', 'Travel', 'Anime', 'Photography'],
    sharedInterests: ['Music', 'Travel'],
    languages: ['Japanese', 'English'],
    bio: 'I love music, anime, and traveling. Excited to learn about different cultures and make new friends around the world!',
    verifiedStudent: true,
    timezone: 'Asia/Tokyo (JST +9:00)',
  },
  {
    id: 'match_emma_02',
    name: 'Emma Wilson',
    age: 20,
    country: 'Canada',
    countryCode: 'CA',
    flag: '🇨🇦',
    educationLevel: 'University',
    institution: 'University of Toronto',
    matchScore: 88,
    avatar: '👩‍🔬',
    gallery: ['🔬 Chemistry Lab', '⛸️ Ice Skating', '📚 Book Debate Club'],
    interests: ['Sports', 'Education', 'Book Stories', 'Science'],
    sharedInterests: ['Sports', 'Science'],
    languages: ['English', 'French'],
    bio: 'Passionate about literature, debate, and winter sports! Looking forward to exchanging global perspectives and learning from peers.',
    verifiedStudent: true,
    timezone: 'America/Toronto (EST -5:00)',
  },
  {
    id: 'match_carlos_03',
    name: 'Carlos Silva',
    age: 19,
    country: 'Brazil',
    countryCode: 'BR',
    flag: '🇧🇷',
    educationLevel: 'College',
    institution: 'University of São Paulo',
    matchScore: 85,
    avatar: '🧑‍🌾',
    gallery: ['⚽ Campus Football', '🌿 Amazon Drones', '☕ Coffee Tasting'],
    interests: ['Football', 'Culture', 'Food & Cooking', 'Sports'],
    sharedInterests: ['Sports', 'Culture'],
    languages: ['Portuguese', 'English', 'Spanish'],
    bio: 'Football enthusiast and amateur chef. Eager to connect, practice my conversational English, and share authentic Brazilian customs!',
    verifiedStudent: true,
    timezone: 'America/Sao_Paulo (BRT -3:00)',
  },
  {
    id: 'match_sofia_04',
    name: 'Sofia Martinez',
    age: 21,
    country: 'Spain',
    countryCode: 'ES',
    flag: '🇪🇸',
    educationLevel: 'University',
    institution: 'Complutense University of Madrid',
    matchScore: 88,
    avatar: '👩‍🎓',
    gallery: ['🏛️ Prado Museum', '💃 Flamenco Dance', '🥘 Tapas Evenings'],
    interests: ['Art', 'Travel', 'Photography', 'Culture'],
    sharedInterests: ['Culture'],
    languages: ['Spanish', 'English', 'Italian'],
    bio: 'Art history enthusiast curious about world heritage architecture, museum curation, and intercultural stories.',
    verifiedStudent: true,
    timezone: 'Europe/Madrid (CET +1:00)',
  },
  {
    id: 'match_liam_05',
    name: "Liam O'Connor",
    age: 20,
    country: 'Ireland',
    countryCode: 'IE',
    flag: '🇮🇪',
    educationLevel: 'College',
    institution: 'Trinity College Dublin',
    matchScore: 85,
    avatar: '🧑‍🚀',
    gallery: ['🪈 Irish Flute', '⚡ Renewable Tech', '🍀 Gaelic Hurling'],
    interests: ['Music', 'Science', 'Environment', 'Technology'],
    sharedInterests: ['Technology', 'Science'],
    languages: ['English', 'Irish'],
    bio: 'Studying environmental engineering, playing traditional Irish flute, and curious about sustainable technology in other nations.',
    verifiedStudent: true,
    timezone: 'Europe/Dublin (GMT +0:00)',
  },
  {
    id: 'match_hiroshi_06',
    name: 'Hiroshi Tanaka',
    age: 20,
    country: 'Japan',
    countryCode: 'JP',
    flag: '🇯🇵',
    educationLevel: 'University',
    institution: 'Tokyo Institute of Technology',
    matchScore: 92,
    avatar: '👨‍💻',
    gallery: ['🤖 Akihabara Tech', '🎮 Game Development', '🍜 Ramen Quest'],
    interests: ['Technology', 'Science', 'Travel', 'Gaming'],
    sharedInterests: ['Technology', 'Science'],
    languages: ['Japanese', 'English'],
    bio: 'Mechanical robotics enthusiast building autonomous drones. Passionate about cross-border engineering collaborations!',
    verifiedStudent: true,
    timezone: 'Asia/Tokyo (JST +9:00)',
  },
];
