// Real database-aligned profiles for Global Student Connect (Elena & Kenji)

export const INITIAL_STUDENT_PROFILE = {
  id: '6aa706129f9197a2c39a93ec',
  _id: '6aa706129f9197a2c39a93ec',
  name: 'Elena Rostova',
  email: 'elena.rostova@student.edu',
  country: 'Germany',
  countryCode: 'DE',
  flag: '🇩🇪',
  age: 21,
  educationLevel: 'Undergraduate - 3rd Year',
  institution: 'Technical University of Munich',
  timezone: 'Europe/Berlin (CET +1:00)',
  bio: 'Computer science major specializing in artificial intelligence and web technologies. Passionate about cross-cultural academic collaboration, hackathons, and learning new languages.',
  avatar: '👩‍🎓',
  profilePicture: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&auto=format&fit=crop&q=80',
  completionPercentage: 100,
  isProfileComplete: true,
  interests: ['Artificial Intelligence', 'Web Development', 'System Architecture', 'Cultural Exchange'],
  languages: ['English', 'German', 'French'],
  stats: {
    totalMatches: 1,
    upcomingCalls: 1,
    reflections: 1,
    countriesConnected: 1,
  },
  upcomingCall: {
    id: 'sess_01',
    partnerName: 'Kenji Takahashi',
    partnerCountry: 'Japan',
    partnerFlag: '🇯🇵',
    partnerAvatar: '👨‍💻',
    date: 'Tomorrow, 4:00 PM',
    topic: 'Web Architecture, Robotics & Cross-Cultural Collaboration',
    meetingId: 'test-room',
  },
};

export const ALL_INTERESTS_LIST = [
  { id: 'tech', name: 'Technology', icon: 'Laptop' },
  { id: 'ai', name: 'Artificial Intelligence', icon: 'Sparkles' },
  { id: 'web', name: 'Web Development', icon: 'Laptop' },
  { id: 'robotics', name: 'Robotics', icon: 'Gamepad2' },
  { id: 'system', name: 'System Architecture', icon: 'FlaskConical' },
  { id: 'culture', name: 'Cultural Exchange', icon: 'Globe' },
  { id: 'science', name: 'Science', icon: 'FlaskConical' },
  { id: 'sports', name: 'Sports', icon: 'Trophy' },
  { id: 'art', name: 'Art', icon: 'Palette' },
  { id: 'travel', name: 'Travel', icon: 'Plane' },
  { id: 'books', name: 'Book Stories', icon: 'BookOpen' },
  { id: 'education', name: 'Education', icon: 'GraduationCap' },
  { id: 'environment', name: 'Environment', icon: 'Leaf' },
  { id: 'music', name: 'Music', icon: 'Music' },
];

// Exactly matching the other authentic account in the database (Kenji Takahashi)
export const MOCK_MATCHES = [
  {
    id: '6aa706129f9197a2c39a93ed',
    _id: '6aa706129f9197a2c39a93ed',
    name: 'Kenji Takahashi',
    email: 'kenji.takahashi@student.edu',
    age: 22,
    country: 'Japan',
    countryCode: 'JP',
    flag: '🇯🇵',
    educationLevel: 'Undergraduate - 4th Year',
    institution: 'Tokyo Institute of Technology',
    matchScore: 95,
    avatar: '👨‍💻',
    gallery: ['🤖 Autonomous Robotics', '🌐 Distributed Systems', '🍵 Cultural Dialogue'],
    interests: ['Software Engineering', 'Robotics', 'Web Development', 'Cultural Exchange'],
    sharedInterests: ['Web Development', 'Cultural Exchange'],
    languages: ['Japanese', 'English'],
    bio: 'Software engineering student passionate about distributed systems, robotics, and interactive UI design. Looking forward to meeting international peers for study sessions and language exchange.',
    verifiedStudent: true,
    timezone: 'Asia/Tokyo (JST +9:00)',
  },
];
